# Generated by Django 4.2 on 2023-04-25 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=30, verbose_name='CNPJ')),
                ('contato', models.CharField(max_length=30, verbose_name='Contato')),
                ('endereco', models.TextField(verbose_name='Endereco')),
                ('area_atuacao', models.CharField(max_length=50, verbose_name='Area de atuacao')),
            ],
            options={
                'db_table': 'tb_estabelecimentos',
            },
        ),
        migrations.CreateModel(
            name='Extintor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('data_validade', models.DateField()),
                ('nivel', models.CharField(max_length=50, verbose_name='Nivel Extintor')),
                ('termo_garantia', models.BooleanField(verbose_name='Termo de Garantia')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Extintor')),
                ('tamanho', models.CharField(max_length=50, verbose_name='Tamanho do extintor')),
                ('local', models.CharField(max_length=100, verbose_name='Local do Extintor')),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='images/qrcode')),
                ('qrcode_link', models.CharField(blank=True, max_length=30, null=True, verbose_name='Link do Qrcode')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estabelecimento')),
            ],
            options={
                'db_table': 'tb_extintores',
            },
        ),
        migrations.CreateModel(
            name='Vistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('informacoes', models.TextField()),
                ('extintor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.extintor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_vistorias',
            },
        ),
        migrations.CreateModel(
            name='Qrcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.ImageField(upload_to='images/qrcode')),
                ('qrcode_link', models.CharField(max_length=30, verbose_name='Link do Qrcode')),
                ('extintor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extintor_qr', to='core.extintor')),
            ],
            options={
                'db_table': 'tb_qrcodes',
            },
        ),
    ]
