# Generated by Django 4.2 on 2023-04-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extintor',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='images/qrcode/'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qrcode',
            field=models.ImageField(upload_to='images/qrcode/'),
        ),
    ]
