# Generated by Django 4.2 on 2023-04-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_extintor_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extintor',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='images/qrcode/'),
        ),
    ]
