# Generated by Django 4.2 on 2023-04-26 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_extintor_qrcode_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extintor',
            name='qrcode_link',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='extintor',
        ),
        migrations.AlterField(
            model_name='extintor',
            name='qrcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.qrcode'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qrcode_link',
            field=models.CharField(max_length=30, verbose_name='Link do Qrcode'),
        ),
    ]
