# Generated by Django 4.2 on 2023-04-26 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_qrcode_qrcode_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='qrcode',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='extintor',
            name='qrcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='qrcode_ext', to='core.qrcode'),
        ),
    ]
