# Generated by Django 4.2.1 on 2023-05-12 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_rename_qrcode_qrcode_image_alter_extintor_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_protocolo', models.CharField(editable=False, max_length=20, unique=True)),
                ('dt_denuncia', models.DateField(auto_now_add=True, null=True)),
                ('local_ocorrencia', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('anexo', models.ImageField(blank=True, null=True, upload_to='images/denuncias/')),
                ('status', models.CharField(choices=[('ANA', 'Análise'), ('ANDA', 'Andamento'), ('CONC', 'CONCLUÍDA')], default='ANA', max_length=5, verbose_name='Status')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_denuncias',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=30, null=True, verbose_name='CNPJ')),
                ('contato', models.CharField(blank=True, max_length=30, null=True, verbose_name='Contato')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereco')),
                ('area_atuacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Area de atuacao')),
            ],
            options={
                'db_table': 'tb_empresas',
            },
        ),
        migrations.CreateModel(
            name='Fiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_fiscal', models.CharField(blank=True, max_length=30, null=True)),
                ('empresa_fiscal', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='extintor',
            name='estabelecimento',
        ),
        migrations.RemoveField(
            model_name='vistoria',
            name='data',
        ),
        migrations.RemoveField(
            model_name='vistoria',
            name='usuario',
        ),
        migrations.AddField(
            model_name='vistoria',
            name='data_agendada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoria',
            name='data_realizada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoria',
            name='resultado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo Extintor'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='data_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de validade'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='local',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Local do Extintor'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='nivel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nivel Extintor'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='tamanho',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tamanho do extintor'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='termo_garantia',
            field=models.BooleanField(blank=True, null=True, verbose_name='Termo de Garantia'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Extintor'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(upload_to='images/qrcode/', verbose_name='Qrcode Imagem'),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='extintor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.extintor'),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='informacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Estabelecimento',
        ),
        migrations.AddField(
            model_name='extintor',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='vistoria',
            name='denuncia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.denuncia'),
        ),
        migrations.AddField(
            model_name='vistoria',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='vistoria',
            name='fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.fiscal'),
        ),
    ]
