# Generated by Django 4.2.1 on 2023-05-20 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_fiscal_usuario_alter_fiscal_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extintor',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa'),
        ),
    ]
