# Generated by Django 4.2.1 on 2023-05-21 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_extintor_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistoriasAgendadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo_agendamento', models.CharField(editable=False, max_length=20, unique=True)),
                ('data_agendada', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CO', 'Confirmada'), ('CA', 'CANCELADA')], default='CO', max_length=5, verbose_name='Status')),
                ('contato', models.CharField(blank=True, max_length=30, null=True, verbose_name='Contato')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa')),
            ],
            options={
                'db_table': 'tb_vistorias_agendamento',
            },
        ),
        migrations.CreateModel(
            name='VistoriasRealizadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_protocolo', models.CharField(editable=False, max_length=20, unique=True)),
                ('data_realizada', models.DateField(auto_now_add=True, null=True)),
                ('bocal_vedado', models.BooleanField(blank=True, null=True)),
                ('indicador_pressao', models.BooleanField(blank=True, null=True)),
                ('pino_seguranca', models.BooleanField(blank=True, null=True)),
                ('selo_certificacao', models.BooleanField(blank=True, null=True)),
                ('local_acesso', models.BooleanField(blank=True, null=True)),
                ('informacoes', models.TextField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('anexos_img', models.ImageField(blank=True, null=True, upload_to='images/vistorias/', verbose_name='Anexos Vistoria')),
                ('extintores', models.ManyToManyField(blank=True, to='core.extintor')),
                ('fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.fiscal')),
            ],
            options={
                'db_table': 'tb_vistorias_realizadas',
            },
        ),
        migrations.DeleteModel(
            name='Vistoria',
        ),
    ]
