# Generated by Django 4.2.1 on 2023-05-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_vistoriasrealizadas_extintores_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vistoriasrealizadas',
            old_name='extintores',
            new_name='extintor',
        ),
    ]
