# Generated by Django 4.1.3 on 2023-05-25 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_vistoriasrealizadas_vistoria_agendada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vistoriasrealizadas',
            name='selo_certificacao',
        ),
    ]
